#!/bin/bash
#SBATCH -J data_convert                        # Job name
#SBATCH -N 1                                 # Total number of nodes requested
#SBATCH -n 4                                 # Total number of cores requested
#SBATCH --get-user-env                       # retrieve the users login environment
#SBATCH --mem=2000                           # server memory requested (per node)
#SBATCH -t 2:00:00                           # Time limit (hh:mm:ss)
#SBATCH --partition=default_partition       # Request partition
#SBATCH --gres=gpu:1080ti:1                  # Type/number of GPUs needed
python3 /home/foodrecognition/scripts/format_data_maskrcnn.py